export const playlist = [
    {
        id: 1,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Guilt',
        author: 'Nero',
        album: 'Welcome Reality',
        like: "img/icon/sprite.svg#icon-like",
        time: '4:44',
    },
    {
        id: 2,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Elektro',
        author: 'Dynoro, Outwork, Mr. Gee',
        album: 'Elektro',
        like: "img/icon/sprite.svg#icon-like",
        time: '2:22',
    },
    {
        id: 3,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'I’m Fire',
        author: 'Ali Bakgor',
        album: 'I’m Fire',
        like: "img/icon/sprite.svg#icon-like",
        time: '2:22',
    },
    {
        id: 4,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Non Stop',
        author: 'Стоункат, Psychopath',
        album: 'Non Stop',
        like: "img/icon/sprite.svg#icon-like",
        time: '4:12',
    },
    {
        id: 5,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Run Run',
        author: 'Jaded, Will Clarke, AR/CO',
        album: 'Run Run',
        like: "img/icon/sprite.svg#icon-like",
        time: '2:54',
    },
    {
        id: 6,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Eyes on Fire (Zeds Dead Remix)',
        author: 'Blue Foundation, Zeds Dead',
        album: 'Eyes on Fire',
        like: "img/icon/sprite.svg#icon-like",
        time: '5:20',
    },
    {
        id: 7,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Mucho Bie',
        author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
        album: 'Mucho Bie',
        like: "img/icon/sprite.svg#icon-like",
        time: '3:41',
    },
    {
        id: 8,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Knives n Cherries',
        author: 'minthaze',
        album: 'Captivating',
        like: "img/icon/sprite.svg#icon-like",
        time: '1:48',
    },
    {
        id: 9,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Knives n Cherries',
        author: 'minthaze',
        album: 'Captivating',
        like: "img/icon/sprite.svg#icon-like",
        time: '1:48',
    },
    {
        id: 10,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Knives n Cherries',
        author: 'minthaze',
        album: 'Captivating',
        like: "img/icon/sprite.svg#icon-like",
        time: '1:48',
    },
    {
        id: 11,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Knives n Cherries',
        author: 'minthaze',
        album: 'Captivating',
        like: "img/icon/sprite.svg#icon-like",
        time: '1:48',
    },
    {
        id: 12,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Knives n Cherries',
        author: 'minthaze',
        album: 'Captivating',
        like: "img/icon/sprite.svg#icon-like",
        time: '1:48',
    },
    {
        id: 13,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Knives n Cherries',
        author: 'minthaze',
        album: 'Captivating',
        like: "img/icon/sprite.svg#icon-like",
        time: '1:48',
    },
    {
        id: 14,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'How Deep Is Your Love',
        author: 'Calvin Harris, Disciples',
        album: 'How Deep Is Your Love',
        like: "img/icon/sprite.svg#icon-like",
        time: '3:32',
    },
    {
        id: 15,
        icon: "img/icon/sprite.svg#icon-note",
        track: 'Morena',
        author: 'Tom Boxer',
        album: 'Soundz Made in Romania',
        like: "img/icon/sprite.svg#icon-like",
        time: '3:36',
    }
]